return {

	
	{
		TypePool	= "Easter Egg",
		Title		= "Arcafanetiz",
		Description = "I was here, this have a 0.001% Chance of appearing btw :^)"
	},
	
	-- Security Department
	{
		TypePool	= "Security Department",
		Title		= "Cameras",
		Description = "You can use the cameras to find enemies on the map."
	},	
	{
		TypePool	= "Security Department",
		Title		= "Testing Security",
		Description = "Work with Scientist to secure their testing."
	},		
	{
		TypePool	= "Security Department",
		Title		= "Help Keep The Game Safe",
		Description = "Report any rule breakers/cheaters to a Game Moderator using our communications server."
	},		
	-- Class - D
	{
		TypePool	= "Class - D",
		Title		= "Escape System",
		Description	= "You can escape as Class - D and find the Chaos Insurgency base to join them!"
	},
	{
		TypePool	= "Class - D",
		Title		= "Help Keep The Game Safe",
		Description = "Report any rule breakers/cheaters to a Game Moderator using our communications server."
	},		
	
	-- Chaos Insurgency
	{
		TypePool	= "Chaos Insurgency",
		Title		= "Secret Entrance",
		Description	= "You can use an escape vent on the right side of the base to sneak in!"
	},
	{
		TypePool	= "Chaos Insurgency",
		Title		= "Recruit Comrades",
		Description	= "Save the Class - D from the foundation and get them to join your team!"
	},
	{
		TypePool	= "Chaos Insurgency",
		Title		= "Help Keep The Game Safe",
		Description = "Report any rule breakers/cheaters to a Game Moderator using our communications server."
	},		
	
	-- Engineering and Technical
	{
		TypePool	= "Engineering and Technical",
		Title		= "Cameras",
		Description	= "Repair the boxes to keep the cameras running!"
	},
	{
		TypePool	= "Engineering and Technical",
		Title		= "Help Keep The Game Safe",
		Description = "Report any rule breakers/cheaters to a Game Moderator using our communications server."
	},		
	
	-- Mobile Task Force
	{
		TypePool	= "Mobile Task Force",
		Title		= "Security",
		Description	= "Protect the front gates to keep intruders out!"
	},
	{
		TypePool	= "Mobile Task Force",
		Title		= "Help Keep The Game Safe",
		Description = "Report any rule breakers/cheaters to a Game Moderator using our communications server."
	},		

	
	-- Scientific Department
	{
		TypePool	= "Scientific Department",
		Title		= "Testing",
		Description	= "Grab a Class - D, and Security, and get to testing!"
	},
	{
		TypePool	= "Scientific Department",
		Title		= "Help Keep The Game Safe",
		Description = "Report any rule breakers/cheaters to a Game Moderator using our communications server."
	},		
	
	
	-- Global Occult Coalition
	{
		TypePool	= "Global Occult Coalition",
		Title		= "Help Keep The Game Safe",
		Description = "Report any rule breakers/cheaters to a Game Moderator using our communications server."
	},		
	
	
	-- O5 Council
	{
		TypePool	= "O5 Council",
		Title		= "Help Keep The Game Safe",
		Description = "Report any rule breakers/cheaters to a Game Moderator using our communications server."
	},		
	
	-- Site Director
	{
		TypePool	= "Site Director",
		Title		= "Help Keep The Game Safe",
		Description = "Report any rule breakers/cheaters to a Game Moderator using our communications server."
	},		

	
};