local ranks = {
	["Class - D"] = {
		{
			title = "Rookie",
			requiredLevel = 1
		},
		{
			title = "Prisoner",
			requiredLevel = 5
		},	
		{
			title = "Delinquent",
			requiredLevel = 10
		},	
		{
			title = "Scum",
			requiredLevel = 15
		},	
		{
			title = "Criminal",
			requiredLevel = 20
		},	
		{
			title = "Lockdown",
			requiredLevel = 25
		},	
		{
			title = "Maximum Security",
			requiredLevel = 30
		},			
	},
	["Security Department"] = {
		{
			title = "Trainee",
			requiredLevel = 1
		},
		{
			title = "Junior Guard",
			requiredLevel = 5
		},	
		{
			title = "Guard",
			requiredLevel = 10
		},	
		{
			title = "Senior Guard",
			requiredLevel = 15
		},	
		{
			title = "Security Corporal",
			requiredLevel = 20
		},	
		{
			title = "Security Lieutenant",
			requiredLevel = 25
		},	
		{
			title = "Head of Security",
			requiredLevel = 30
		},	
	},
	["Mobile Task Force"] = {
		{
			title = "Trainee",
			requiredLevel = 1
		},
		{
			title = "Private",
			requiredLevel = 5
		},	
		{
			title = "Corporal",
			requiredLevel = 10
		},	
		{
			title = "Sergeant",
			requiredLevel = 15
		},	
		{
			title = "Lieutenant",
			requiredLevel = 20
		},	
		{
			title = "Captain",
			requiredLevel = 25
		},	
		{
			title = "Major",
			requiredLevel = 30
		},	
	},
	["Global Occult Coalition"] = {
		{
			title = "Trainee",
			requiredLevel = 1
		},
		{
			title = "Private",
			requiredLevel = 5
		},	
		{
			title = "Corporal",
			requiredLevel = 10
		},	
		{
			title = "Sergeant",
			requiredLevel = 15
		},	
		{
			title = "Lieutenant",
			requiredLevel = 20
		},	
		{
			title = "Captain",
			requiredLevel = 25
		},	
		{
			title = "Major",
			requiredLevel = 30
		},	
	},
	["Scientific Department"] = {
		{
			title = "Entrant",
			requiredLevel = 1
		},
		{
			title = "Junior Researcher",
			requiredLevel = 5
		},	
		{
			title = "Researcher",
			requiredLevel = 10
		},	
		{
			title = "Experienced Researcher",
			requiredLevel = 15
		},	
		{
			title = "Senior Researcher",
			requiredLevel = 20
		},	
		{
			title = "Head Researcher",
			requiredLevel = 25
		},	
		{
			title = "Chief Researcher",
			requiredLevel = 30
		},				
	},
	["Chaos Insurgency"] = {
		{
			title = "Escaped Convict",
			requiredLevel = 1
		},
		{
			title = "Initiate",
			requiredLevel = 5
		},	
		{
			title = "Sigma",
			requiredLevel = 10
		},	
		{
			title = "Delta",
			requiredLevel = 15
		},	
		{
			title = "Gamma",
			requiredLevel = 20
		},	
		{
			title = "Beta",
			requiredLevel = 25
		},	
		{
			title = "Alpha",
			requiredLevel = 30
		},				
	},
	["Engineering and Technical"] = {
		{
			title = "Trainee",
			requiredLevel = 1
		},
		{
			title = "Jr. Engineer",
			requiredLevel = 5
		},	
		{
			title = "Sr. Engineer",
			requiredLevel = 10
		},	
		{
			title = "Adv. Engineer",
			requiredLevel = 15
		},	
		{
			title = "Master Engineer",
			requiredLevel = 20
		},	
		{
			title = "Chief Engineer",
			requiredLevel = 25
		},	
		{
			title = "Site Engineer",
			requiredLevel = 30
		},					
	},
	["Site Director"] = {
		{
			title = "Site Director",
			requiredLevel = 1
		},
	},
	["O5 Council"] = {
		{
			title = "O5 Council",
			requiredLevel = 1
		},
	},
}

return ranks
