return {
	["Stitchface"] = {
		DisplayName = "Stitchface",
		Id = 8329679,
	},
	["Err"] = {
		DisplayName = "Err",
		Id = 20418658,
	},
	["Big Sad Eyes"] = {
		DisplayName = "Big Sad Eyes",
		Id = 391496223,
	},	
	["Whistle"] = {
		DisplayName = "Whistle",
		Id = 22877700,
	},
	["Sinister"] = {
		DisplayName = "Sinister",
		Id = 8329686,
	},
	["Squiggle Mouth"] = {
		DisplayName = "Squiggle Mouth",
		Id = 25166274,
	},
	["Laughing Fun"] = {
		DisplayName = "Laughing Fun",
		Id = 226217449,
	},	
	["Classic Vampire"] = {
		DisplayName = "Classic Vampire",
		Id = 7074836,
	},		
	["Yawn"] = {
		DisplayName = "Yawn",
		Id = 162068415,
	},		
	["Freckles"] = {
		DisplayName = "Freckles",
		Id = 12145366,
	},		
	["Winky"] = {
		DisplayName = "Winky",
		Id = 7074864,
	},	
	["Glee"] = {
		DisplayName = "Glee",
		Id = 7074729,
	},		
	[":-/"] = {
		DisplayName = ":-/",
		Id = 7075469,
	},	
	["Hold It In"] = {
		DisplayName = "Hold It In",
		Id = 2222771916,
	},	
	["Shiny Teeth"] = {
		DisplayName = "Shiny Teeth",
		Id = 20722130,
	},
	["Know-It-All Grin"] = {
		DisplayName = "Know-It-All Grin",
		Id = 26424808,
	},	
	["Serious Scar Face"] = {
		DisplayName = "Serious Scar Face",
		Id = 255827175,
	},	
	["Anguished"] = {
		DisplayName = "Anguished",
		Id = 8560975,
	},		
	["Suspicious"] = {
		DisplayName = "Suspicious",
		Id = 209994929,
	},
	["Sick Day"] = {
		DisplayName = "Sick Day",
		Id = 26619096,
	},
	["Braces"] = {
		DisplayName = "Braces",
		Id = 30394484,
	},
	["Puck"] = {
		DisplayName = "Puck",
		Id = 20298988,
	},
	["Joyful Smile"] = {
		DisplayName = "Joyful Smile",
		Id = 209995366,
	},
	["Happy Wink"] = {
		DisplayName = "Happy Wink",
		Id = 236399287,
	},
	["Disbelief"] = {
		DisplayName = "Disbelief",
		Id = 20337343,
	},
	["WHAAAaaa!"] = {
		DisplayName = "WHAAAaaa!",
		Id = 14127194,
	},
	["Tired Face"] = {
		DisplayName = "Tired Face",
		Id = 141728790,
	},
	["Good Intentioned"] = {
		DisplayName = "Good Intentioned",
		Id = 7317793,
	},
	["Skeptic"] = {
		DisplayName = "Skeptic",
		Id = 31117267,
	},
	["Not sure if..."] = {
		DisplayName = "Not sure if...",
		Id = 173789324,
	},
	["Drool"] = {
		DisplayName = "Drool",
		Id = 7074893,
	},
	["Heeeeeey..."] = {
		DisplayName = "Heeeeeey...",
		Id = 21635565,
	},
	["Sadfaic"] = {
		DisplayName = "Sadfaic",
		Id = 117522793,
	},
	["Just Trouble"] = {
		DisplayName = "Just Trouble",
		Id = 244160766,
	},
	["Nouveau George"] = {
		DisplayName = "Nouveau George",
		Id = 398675764,
	},
	["Concerned"] = {
		DisplayName = "Concerned",
		Id = 9250660,
	},
	["Huh?"] = {
		DisplayName = "Huh?",
		Id = 150182466,
	},
	["Grr!"] = {
		DisplayName = "Grr!",
		Id = 19398554,
	},
	["Poor Man"] = {
		DisplayName = "Poor Man",
		Id = 7699183,
	},
	["Furious George"] = {
		DisplayName = "Furious George",
		Id = 277950647,
	},
	["Wink-Blink"] = {
		DisplayName = "Wink-Blink",
		Id = 22828351,
	},
	["Sad"] = {
		DisplayName = "Sad",
		Id = 7699177,
	},
	["Face of Disappointment"] = {
		DisplayName = "Face of Disappointment",
		Id = 209994270,
	},
	["Singing"] = {
		DisplayName = "Singing",
		Id = 66330310,
	},
	["Angry Zombie"] = {
		DisplayName = "Angry Zombie",
		Id = 173789114,
	},
	["Sigmund"] = {
		DisplayName = "Sigmund",
		Id = 21311601,
	},
	["Drill Sergeant"] = {
		DisplayName = "Drill Sergeant",
		Id = 141728899,
	},
	["I Didn't Eat That Cookie"] = {
		DisplayName = "I Didn't Eat That Cookie",
		Id = 116042990,
	},
	["Awkward Eyeroll"] = {
		DisplayName = "Awkward Eyeroll",
		Id = 150182378,
	},
	["Raig Face"] = {
		DisplayName = "Raig Face",
		Id = 209994783,
	},
	["Smug"] = {
		DisplayName = "Smug",
		Id = 406001308,
	},
	["Daring Beard"] = {
		DisplayName = "Daring Beard",
		Id = 110288809,
	},
	["I Am Not Amused"] = {
		DisplayName = "I Am Not Amused",
		Id = 7131886,
	},
	["Awkward...."] = {
		DisplayName = "Awkward....",
		Id = 23932048,
	},
	["I Hate Noobs"] = {
		DisplayName = "I Hate Noobs",
		Id = 14030577,
	},
	["Existential Angst"] = {
		DisplayName = "Existential Angst",
		Id = 7074814,
	},
	["Silence"] = {
		DisplayName = "Silence",
		Id = 10860397,
	},
	["Don't Wake Me Up"] = {
		DisplayName = "Don't Wake Me Up",
		Id = 343619993,
	},
	["And then we'll take over"] = {
		DisplayName = "And then we'll take over",
		Id = 12732366,
	},
	["Sad Zombie"] = {
		DisplayName = "Sad Zombie",
		Id = 7131361,
	},
	["Yawnnn"] = {
		DisplayName = "Yawnnn",
		Id = 20010377,
	},
	["Sneaky Steve"] = {
		DisplayName = "Sneaky Steve",
		Id = 823012694,
	},
	["Crazy Happy"] = {
		DisplayName = "Crazy Happy",
		Id = 45515121,
	},
	["Sly Guy Face"] = {
		DisplayName = "Sly Guy Face",
		Id = 238983378,
	},
	["Sweat It Out"] = {
		DisplayName = "Sweat It Out",
		Id = 20909103,
	},
	["Too Much Candy"] = {
		DisplayName = "Too Much Candy",
		Id = 295763789,
	},
	["ROAR!!!"] = {
		DisplayName = "ROAR!!!",
		Id = 406001167,
	},	
	["So Funny"] = {
		DisplayName = "So Funny",
		Id = 32058239,
	},
}