return {
	["Ivory"] = {
		DisplayName = "Ivory",
		Color = Color3.fromRGB(234,203,168),
		-- Object
	},	
	["Porcelain"] = {
		DisplayName = "Porcelain",
		Color = Color3.fromRGB(238,208,184),
	},
	["Pale Ivory"] = {
		DisplayName = "Pale Ivory",
		Color = Color3.fromRGB(247,221,196),
	},
	["Warm Ivory"] = {
		DisplayName = "Warm Ivory",
		Color = Color3.fromRGB(247,226,171),
	},
	["Sand"] = {
		DisplayName = "Sand",
		Color = Color3.fromRGB(238,199,148),
	},
	["Rose Beige"] = {
		DisplayName = "Rose Beige",
		Color = Color3.fromRGB(240,192,138),
	},
	["Limestone"] = {
		DisplayName = "Limestone",
		Color = Color3.fromRGB(231,188,145),
	},
	["Beige"] = {
		DisplayName = "Beige",
		Color = Color3.fromRGB(236,191,131),
	},
	["Sienna"] = {
		DisplayName = "Sienna",
		Color = Color3.fromRGB(207,158,124),
	},
	["Honey"] = {
		DisplayName = "Honey",
		Color = Color3.fromRGB(203,150,97),
	},
	["Band"] = {
		DisplayName = "Band",
		Color = Color3.fromRGB(172,139,100),
	},
	["Almond"] = {
		DisplayName = "Almond",
		Color = Color3.fromRGB(148,97,60),
	},
	["Chestnut"] = {
		DisplayName = "Chestnut",
		Color = Color3.fromRGB(137,85,50),
	},
	["Bronze"] = {
		DisplayName = "Bronze",
		Color = Color3.fromRGB(119,68,31),
	},
	["Umber"] = {
		DisplayName = "Umber",
		Color = Color3.fromRGB(178,106,73),
	},
	["Golden"] = {
		DisplayName = "Golden",
		Color = Color3.fromRGB(128,74,42),
	},
	["Expresso"] = {
		DisplayName = "Expresso",
		Color = Color3.fromRGB(98,58,24),
	},
	["Brown"] = {
		DisplayName = "Brown",
		Color = Color3.fromRGB(48,30,16),
	}
}